version: 2.1 # 2.1 config required to use orbs

orbs:
  aws-ecr: circleci/aws-ecr@8.1.0 # use the AWS ECR orb
  aws-ecs: circleci/aws-ecs@3.2.0 # use the AWS ECS orb
  aws-cli: circleci/aws-cli@4.1.2


jobs:
  show-ecr-uri:
    docker:
      - image: amazon/aws-cli:latest
    steps:
      - checkout
      - run: 
          name: Save the Image URI into an environment variable
          command: >
            ECR_URI=$(aws ecr describe-images --repository-name ${MY_APP_PREFIX} \
              --region ${AWS_REGION} \
              --query 'imageDetails[-1].imageTags[0]' --output text)
            echo "export ECR_URI='${ECR_URI}'" >> "$BASH_ENV"
      - run: 
          name: Echo the variable
          command: echo ${ECR_URI}
      - run: 
          name: Echo the variable
          command: echo ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${MY_APP_PREFIX}:${ECR_URI}
  test:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: 
          name: Run npm test
          command: npm /app/test
            
workflows:
  build-and-deploy:
    jobs:
      - test
      - aws-ecr/build-and-push-image: # orb built-in job
          repo: '${MY_APP_PREFIX}'
          tag: '${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update: # orb built-in job
          requires:
            - aws-ecr/build-and-push-image
          family: '${MY_APP_PREFIX}-service'
          cluster: '${MY_APP_PREFIX}'
          container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'
      - show-ecr-uri:
          requires:
            - aws-ecs/deploy-service-update
            - aws-ecr/build-and-push-image